supp1_figs:
	rm -f figs_supp1_CitedByN*.pdf
	pdftools remove -o figs_supp1_CitedByN_tmp.pdf JRSM_1456_iCite_supp1_CitedByN.pdf 1-7
	pdftools remove -o figs_supp1_CitedByN.pdf figs_supp1_CitedByN_tmp.pdf 18

clean:
	rm -f figs_supp1_CitedByN*.pdf

# Copyright (C) 2021-present, DV Klopfenstein. All rights reserved.
